drop database Empleados

create database Empleados
go

use Empleados
go

CREATE TABLE empleados (
IDEMPLEADO INT PRIMARY KEY IDENTITY NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
APPAT VARCHAR(35) NOT NULL,
APMAT VARCHAR(35) NOT NULL,
DIREC VARCHAR(35) NOT NULL,
SUELDO decimal(18,2) NOT NULL,
EDAD int NOT NULL,
FECNAC date NOT NULL,
DULCERIA VARCHAR(35) NOT NULL,)
go

CREATE TABLE USUARIOS (
IDUSUARIOS VARCHAR(15) PRIMARY KEY NOT NULL,
IDEMPLEADO INT NOT NULL,
NOMBRE VARCHAR(35) NOT NULL,
CONTRA VARCHAR(35) NOT NULL,
FECVENTO DATE NOT NULL,
ESTATUS VARCHAR(1) NOT NULL,
CONSTRAINT fk_USUARIOEMPLEADOS FOREIGN KEY (IDEMPLEADO) REFERENCES empleados (IDEMPLEADO))
go

insert into empleados values('Jose Juan' , 'Garcia' , 'Anaya' , 'Cuautitlan' , '25072021' , '20' , '2000-12-22','DULCERIAJJ')
insert into USUARIOS values('jj22',1,'jj','1234','2020-10-09','S')
go
