package respaldosmysqlframe;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M U K E
 */
public class RespyRest extends javax.swing.JFrame {

    public String var1, var2, var3;

    public RespyRest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String nulo = " ";

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Respaldar = new javax.swing.JButton();
        Btn_Restaurar = new javax.swing.JButton();
        Btn_Ver = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT1 = new javax.swing.JTextField();
        TXT2 = new javax.swing.JTextField();
        TXT3 = new javax.swing.JTextField();
        TXT4 = new javax.swing.JTextField();
        Btn_Salir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Btn_Respaldar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Respaldar.setText("Respaldar");
        Btn_Respaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RespaldarActionPerformed(evt);
            }
        });

        Btn_Restaurar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Restaurar.setText("Restaurar");
        Btn_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RestaurarActionPerformed(evt);
            }
        });

        Btn_Ver.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Ver.setText("Ver");
        Btn_Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerActionPerformed(evt);
            }
        });

        Btn_Salir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Respaldo");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Archivo");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Restaura");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Archivos");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Gonzalez Rivera Erick Miguel 652");

        TXT1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXT1.setForeground(new java.awt.Color(51, 51, 51));
        TXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT1ActionPerformed(evt);
            }
        });

        TXT2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXT2.setForeground(new java.awt.Color(51, 51, 51));
        TXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT2ActionPerformed(evt);
            }
        });

        TXT3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXT3.setForeground(new java.awt.Color(51, 51, 51));
        TXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT3ActionPerformed(evt);
            }
        });

        TXT4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TXT4.setForeground(new java.awt.Color(51, 51, 51));
        TXT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT4ActionPerformed(evt);
            }
        });

        Btn_Salir1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Salir1.setText("Limpiar");
        Btn_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Salir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Respaldar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Restaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Btn_Restaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Respaldar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Ver)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TXT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Btn_Salir1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_Salir)
                                    .addComponent(TXT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT4ActionPerformed
        // TODO add your handling code here:
        TXT4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (TXT4.getText().equals(nulo)) {
                    JOptionPane.showMessageDialog(null, "EL NOMBRE DE LA BASE DE DATOS ES OBLIGATORIO");
                } else {
                    TXT1.requestFocusInWindow();
                }
            }
        });
    }//GEN-LAST:event_TXT4ActionPerformed

    private void TXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT2ActionPerformed
        // TODO add your handling code here:
        var2 = TXT2.getText();
        TXT2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (TXT2.getText().equals(nulo)) {
                    JOptionPane.showMessageDialog(null, "EL NOMBRE DE LA BASE DE DATOS ES OBLIGATORIO");
                } else {
                    TXT3.requestFocusInWindow();
                }
            }
        });
    }//GEN-LAST:event_TXT2ActionPerformed

    private void Btn_VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerActionPerformed
        // TODO add your handling code here:
        //Btn_Ver
        var1 = (this.TXT1.getText());
        try {
            String url = "C:/Users/M U K E/Documents/PROGRAMACION/POO/RespaldosMySQLFrame/ " + var1 + ".sql";
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe", "/c", url);
            p.start();

        } catch (IOException ex) {
            Logger.getLogger(RespyRest.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_VerActionPerformed

    private void Btn_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RestaurarActionPerformed
        //Btn_Restauracion
        RestaurarMySQLFrame btn_Resta = new RestaurarMySQLFrame();
        btn_Resta.setBaseData(this.TXT2.getText());
        btn_Resta.setQuery(this.TXT3.getText());
        btn_Resta.Rest();
        JOptionPane.showMessageDialog(null, "EL REGISTRO FUE ACEPTADO");
    }//GEN-LAST:event_Btn_RestaurarActionPerformed

    private void Btn_RespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RespaldarActionPerformed
        // TODO add your handling code here:
        RespaldosMySQLFrame btn_Resp = new RespaldosMySQLFrame();
        btn_Resp.setBaseData(this.TXT4.getText());
        btn_Resp.setQuery(this.TXT1.getText());
        btn_Resp.Resp();
        JOptionPane.showMessageDialog(null, "COPIA DE SEGURIDAD ACEPTADA");
    }//GEN-LAST:event_Btn_RespaldarActionPerformed

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        //Btn_Salir
        int salir = JOptionPane.showConfirmDialog(null, "En verdad deseas salir");
        if (salir == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void TXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT1ActionPerformed
        // TODO add your handling code here:
        var1 = TXT1.getText();
        TXT1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (TXT1.getText().equals(nulo)) {
                    JOptionPane.showMessageDialog(null, "EL NOMBRE DEL ARCHIVO ES OBLIGATORIO");
                } else {
                    Btn_Respaldar.requestFocusInWindow();
                }
            }
        });
    }//GEN-LAST:event_TXT1ActionPerformed

    private void TXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT3ActionPerformed
        // TODO add your handling code here:

        TXT3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (TXT3.getText().equals(nulo)) {
                    JOptionPane.showMessageDialog(null, "EL NOMBRE DEL ARCHIVO ES OBLIGATORIO");
                } else {
                    Btn_Restaurar.requestFocusInWindow();
                }
            }
        });
    }//GEN-LAST:event_TXT3ActionPerformed

    private void Btn_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Salir1ActionPerformed
        // TODO add your handling code here:
        TXT1.setText(nulo);
        TXT2.setText(nulo);
        TXT3.setText(nulo);
        TXT4.setText(nulo);

        TXT4.requestFocusInWindow();
    }//GEN-LAST:event_Btn_Salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespyRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespyRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespyRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespyRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RespyRest().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Respaldar;
    private javax.swing.JButton Btn_Restaurar;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_Salir1;
    private javax.swing.JButton Btn_Ver;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT2;
    private javax.swing.JTextField TXT3;
    private javax.swing.JTextField TXT4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
